name: Simple CI Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: 3.10
    
    - name: Cache pip dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Check Python syntax
      run: |
        python -m py_compile src/*.py web_interface.py main.py
        echo "✅ All Python files have valid syntax"
    
    - name: Run basic tests
      run: |
        echo "Running basic functionality tests..."
        python -c "from src.analyzer import PcapAnalyzer; print('✅ Analyzer module imported successfully')"
        python -c "from src.risk_calculator import RiskCalculator; print('✅ Risk calculator module imported successfully')"
        python -c "from src.enhanced_report_generator import EnhancedReportGenerator; print('✅ Report generator module imported successfully')"
        echo "✅ All core modules imported successfully"
    
    - name: Check file structure
      run: |
        echo "Checking project structure..."
        ls -la
        echo "✅ Project structure verified"

  security:
    runs-on: ubuntu-latest
    needs: test
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: 3.10
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Basic security check
      run: |
        echo "Running basic security checks..."
        # Check for common security issues
        if grep -r "password.*=" src/ 2>/dev/null; then
          echo "⚠️  Potential hardcoded passwords found"
        else
          echo "✅ No hardcoded passwords found"
        fi
        
        if grep -r "api_key.*=" src/ 2>/dev/null; then
          echo "⚠️  Potential hardcoded API keys found"
        else
          echo "✅ No hardcoded API keys found"
        fi
        
        echo "✅ Basic security checks completed"

  deploy:
    runs-on: ubuntu-latest
    needs: [test, security]
    if: github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Deploy to Vercel
      uses: amondnet/vercel-action@v25
      with:
        vercel-token: ${{ secrets.VERCEL_TOKEN }}
        vercel-org-id: ${{ secrets.ORG_ID }}
        vercel-project-id: ${{ secrets.PROJECT_ID }}
        vercel-args: '--prod'
