name: Verify

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  verify:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.10
    
    - name: Install
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Verify
      run: |
        python tests/test_basic.py
